# name: Github Pages deploy
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [15.x]

#     steps:
#     - uses: actions/checkout@v1

#     - name: Install Packages
#       run: npm install

#     - name: Build
#       run: npm run build

#     - name: Deploy to GH Pages
#       uses: JamesIves/github-pages-deploy-action@releases/v3
#       with:
#         GITHUB_TOKEN: ${{ secrets.TOKEN }}
#         BRANCH: gh-pages
#         FOLDER: build

name: Deploy to React GitHub Pages

  on:
    # Trigger the workflow every time you push to the `main` branch
    push:
      branches: [ main ]
    # Allows you to run this workflow manually from the Actions tab on GitHub.
    workflow_dispatch:

    # Allow this job to clone the repo and create a page deployment
  permissions:
    contents: read
    pages: write
    id-token: write

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Check out your repository using git
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React
        run: npm run build --if-present

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

    deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v1
   